language: node_js
node_js:
- "node"
- lts/*

cache: npm

install:
 - npm install

script:
  - npm run lint
  - npm run test:unit
  - npm run build
  - npm run docs:build

after_script:
  - cat ./coverage/lcov.info | coveralls

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
keep_history: true
local_dir: docs/.vuepress/dist
on:
  branch: master